# Generated by Django 5.0.4 on 2024-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttributeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("third_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=255,
                    ),
                ),
                ("num_doc", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DigitalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_data_object",
                    models.CharField(
                        choices=[
                            ("subject", "Субъект"),
                            ("object", "Объект"),
                            ("document", "Документ"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "name_data_object",
                    models.CharField(
                        choices=[
                            ("passenger", "Пассажир"),
                            ("carrier", "Перевозчик"),
                            ("patient", "Пациент"),
                            ("doctor", "Врач"),
                            ("pensioner", "Пенсионер"),
                            ("building", "Здание"),
                            ("land", "Земельный участок"),
                            ("vehicle", "Транспортное средство"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description_data_object", models.CharField(max_length=255)),
            ],
        ),
    ]
