# Generated by Django 5.0.4 on 2024-04-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_attributedata_digital_data_referenceinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributedata",
            name="digital_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.digitaldata"
            ),
        ),
        migrations.AlterField(
            model_name="referenceinfo",
            name="digital_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.digitaldata"
            ),
        ),
    ]
