# Generated by Django 5.0.4 on 2024-04-04 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_attributedata_digital_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributedata",
            options={
                "verbose_name": "Данные атрибута",
                "verbose_name_plural": "Данные атрибутов",
            },
        ),
        migrations.AlterModelOptions(
            name="digitaldata",
            options={
                "verbose_name": "Цифровые данные",
                "verbose_name_plural": "Цифровые данные",
            },
        ),
        migrations.AlterModelOptions(
            name="referenceinfo",
            options={
                "verbose_name": "Справочная информация",
                "verbose_name_plural": "Справочные информации",
            },
        ),
    ]
