# Generated by Django 5.0.4 on 2024-04-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_attributedata_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referenceinfo",
            name="digital_data",
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data_source", models.CharField(default="FRSP", max_length=255)),
                (
                    "level_use_data",
                    models.CharField(
                        choices=[
                            ("republic", "Республиканский"),
                            ("local", "Местный"),
                            (
                                "nonused",
                                "Данные на межведомственном уровне не используются",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "choice_type_data",
                    models.CharField(
                        choices=[
                            ("paper", "В бумажном виде"),
                            ("digital", "В электронном виде"),
                            ("combine", "Комбинированный"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("private", "Ограниченный доступ"),
                            ("public", "Доступ без ограничений"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "perm_data",
                    models.CharField(
                        choices=[
                            ("private", "Ограниченный доступ"),
                            ("public", "Доступ без ограничений"),
                        ],
                        max_length=255,
                    ),
                ),
                ("npa", models.TextField()),
                (
                    "data_object",
                    models.CharField(
                        choices=[
                            ("individuals", "Физические лица"),
                            ("legal", "Юридические лица"),
                            ("property", "Имущество"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "period_update",
                    models.CharField(
                        choices=[
                            ("", "Не установлена"),
                            ("", "По мере необходимости"),
                            ("", "По мере поступления данных"),
                            ("", "Непрерывное обновление"),
                            ("", "Установлена НПА"),
                        ],
                        max_length=255,
                    ),
                ),
                ("graph_update", models.TextField(max_length=255)),
                ("len_update", models.TextField(max_length=255)),
                ("npa_collection", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_passports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="accessible_passports", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорты",
            },
        ),
        migrations.CreateModel(
            name="PassportDataStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "information_system_name",
                    models.CharField(
                        choices=[
                            (
                                "mob_depart",
                                'Информационная система "Мобильное правительство"',
                            )
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "bd_name",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlite3", "SQLite3"),
                            ("oracle", "Oracle"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=255,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("table_description", models.TextField()),
                ("table_type", models.CharField(max_length=255)),
                ("column_id", models.IntegerField()),
                ("column_name", models.CharField(max_length=255)),
                ("column_type", models.CharField(max_length=255)),
                ("column_description", models.TextField()),
                ("reference_tbl_clmn", models.URLField(blank=True, null=True)),
                ("flk", models.CharField(max_length=255)),
                ("clmn_key_type", models.CharField(max_length=255)),
                ("teg", models.CharField(max_length=255)),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.passport"
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание структуры данных",
                "verbose_name_plural": "Описание структуры данных",
            },
        ),
        migrations.DeleteModel(
            name="AttributeData",
        ),
        migrations.DeleteModel(
            name="DigitalData",
        ),
        migrations.DeleteModel(
            name="ReferenceInfo",
        ),
    ]
