# Generated by Django 5.0.4 on 2024-04-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_referenceinfo_digital_data_passport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessGlossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("termin", models.TextField()),
                ("national_name", models.TextField()),
                ("alternative_name", models.TextField()),
                ("acronym", models.TextField()),
                ("abbreviation", models.TextField()),
                ("previous_title", models.TextField()),
                ("definition", models.TextField()),
                ("definition_source", models.TextField()),
                ("details", models.TextField()),
                ("hyperlink", models.TextField()),
                (
                    "term_status",
                    models.CharField(
                        choices=[
                            ("valid", "Действующий"),
                            ("invalid", "Не действующий"),
                        ],
                        max_length=255,
                    ),
                ),
                ("availability_of_the_term", models.BooleanField(default=False)),
                (
                    "passport_data_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.passportdatastructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бизнес Глоссарий",
                "verbose_name_plural": "Бизнес Глоссарий",
            },
        ),
    ]
