# Generated by Django 5.0.4 on 2024-04-18 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_businessglossary_passport_data_structure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="administrative_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="deadline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "ежемесячная"),
                    ("quarterly", "ежеквартальная"),
                    ("semi", "полугодичная"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="passport",
            name="persons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Респонденты",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passport",
            name="report_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passport",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[("bvu", "БВУ"), ("so", "СО"), ("rcb", "РЦБ"), ("mfo", "МФО")],
                max_length=255,
                null=True,
            ),
        ),
    ]
