# Generated by Django 5.0.4 on 2024-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_passport_administrative_data_passport_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("pervak", "Первичные данные"),
                    ("vtoryak", "Агрегированные данные"),
                ],
                max_length=255,
            ),
        ),
    ]
