# Generated by Django 5.0.4 on 2024-04-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DataPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=255)),
                (
                    "DATA_LEVEL",
                    models.CharField(
                        choices=[
                            ("republican", "Республиканский"),
                            ("local", "Местный"),
                            (
                                "none",
                                "Данные на межведомственном уровне не используются",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "storage_method",
                    models.CharField(
                        choices=[
                            ("paper", "В бумажном виде"),
                            ("electronic", "В электронном виде"),
                            ("combined", "Комбинированный"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_form",
                    models.CharField(
                        choices=[
                            ("primary", "Первичные данные"),
                            ("aggregated", "Агрегированные данные"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_access",
                    models.CharField(
                        choices=[
                            ("limited", "Ограниченный доступ"),
                            ("unrestricted", "Доступ без ограничений"),
                        ],
                        max_length=50,
                    ),
                ),
                ("users_according_to_npa", models.TextField()),
                ("data_source_according_to_npa", models.TextField()),
                ("actual_data_sources", models.TextField()),
                (
                    "description_objects",
                    models.CharField(
                        choices=[
                            ("individuals", "Физические лица"),
                            ("legal_entities", "Юридические лица"),
                            ("property", "Имущество"),
                            ("results_of_work", "Результаты работ"),
                            (
                                "intellectual_property",
                                "Охраняемые результаты интеллектуальной деятельности и приравненные к ним средства индивидуализации",
                            ),
                            ("intangible_assets", "Нематериальные блага"),
                        ],
                        max_length=50,
                    ),
                ),
                ("update_frequency", models.CharField(max_length=255)),
                ("update_schedule", models.CharField(max_length=255)),
                ("update_order", models.CharField(max_length=255)),
                ("npa_list_for_data_collection_and_processing", models.TextField()),
                ("npa_list_for_data_entry_and_consumption", models.TextField()),
                (
                    "npa_list_for_data_entry_and_consumption_restrictions",
                    models.TextField(),
                ),
                ("data_class", models.CharField(max_length=255)),
                ("creation_date", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт данных",
                "verbose_name_plural": "Паспорт данных",
            },
        ),
    ]
